 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BookTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTable()
        {
            this.BookFineTables = new HashSet<BookFineTable>();
            this.BookReturnTables = new HashSet<BookReturnTable>();
            this.IssueBookTables = new HashSet<IssueBookTable>();
            this.PurchaseDetailTables = new HashSet<PurchaseDetailTable>();
            this.PurTemDetailsTables = new HashSet<PurTemDetailsTable>();
        }
    
        public int BookID { get; set; }
        public int UserID { get; set; }

        [Required(ErrorMessage = "Proszê wybraæ dzia³")]
        public int DepartmentID { get; set; }

        [Required(ErrorMessage = "Proszê kategoriê ksi¹¿ki")]
        public int BookTypeID { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ tytu³ ksi¹¿ki")]
        public string BookTitle { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ krótki opis ksi¹¿ki")]
        [DataType(DataType.MultilineText)]
        public string ShortDescription { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ autora ksi¹¿ki")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ wydawnictwo")]
        public string BookName { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ edycjê ksi¹¿ki")]
        public double Edition { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ liczbê kopii ksi¹¿ki")]
        public int TotalCopies { get; set; }

        [Required(ErrorMessage = "Proszê wybraæ datê rejetracji ksi¹¿ki")]
        [DataType(DataType.Date)]
        public System.DateTime RegDate { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ cenê ksi¹¿ki")]
        public double Price { get; set; }

        [Required(ErrorMessage = "Proszê wpisaæ opis ksi¹¿ki")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookFineTable> BookFineTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookReturnTable> BookReturnTables { get; set; }
        public virtual BookTypeTable BookTypeTable { get; set; }
        public virtual DepartmentTable DepartmentTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IssueBookTable> IssueBookTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetailTable> PurchaseDetailTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurTemDetailsTable> PurTemDetailsTables { get; set; }
    }
}
